// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALsvqD5us9RlQb7hjmOloJ91UeKScvcTE',
    appId: '1:65968445622:web:e7ea964a17d554b25c2e17',
    messagingSenderId: '65968445622',
    projectId: 'crud-18111',
    authDomain: 'crud-18111.firebaseapp.com',
    storageBucket: 'crud-18111.appspot.com',
    measurementId: 'G-NEBWEVWBMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNbGFI3tQdJimodj1GQpQZGp0rjkqamc',
    appId: '1:65968445622:android:94c8b646c6165ffb5c2e17',
    messagingSenderId: '65968445622',
    projectId: 'crud-18111',
    storageBucket: 'crud-18111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRcLe-weiViDE3yqKzPZ0tvwHQzNMsNI',
    appId: '1:65968445622:ios:7866bb44350d737a5c2e17',
    messagingSenderId: '65968445622',
    projectId: 'crud-18111',
    storageBucket: 'crud-18111.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRcLe-weiViDE3yqKzPZ0tvwHQzNMsNI',
    appId: '1:65968445622:ios:a92e49f6c4572daf5c2e17',
    messagingSenderId: '65968445622',
    projectId: 'crud-18111',
    storageBucket: 'crud-18111.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
